main:
  components_repository: "https://github.com/EdgarDmonkey/portfolio"
  streamlit: "https://streamlit.io/"
  copyright: "Edgar Adrian Castro Romero 2024"
  project_name: Portfolio

styling:
  pages: ["About Me","Portfolio"]

docs:
  cv: "docs/Resume_DA.pdf"

images:
  picprofile: "images/pic_portfolio.png"
  picpro: "images/pic_portfolio.jpg"